class MappingIndex:
    DATE = 0
    MAXIMUM_TEMPERATURE = 1
    MINIMUM_TEMPERATURE = 3
    HUMIDITY = 7
    SLICED_DATE = 2
    AVERAGE_TEMPERATURE = 2
    AVERAGE_HUMIDITY = 8
    WEATHER_DIR = "weatherfiles"
    RED_COLOR_CODE = '\033[91m'
    BLUE_COLOR_CODE = '\033[34m'
    RESET_COLOR_CODE = '\033[0m'
    INDEX_ZERO = 0
    INDEX_ONE = 0
    INDEX_TOW = 2
    INDEX_THREE = 3
    INDEX_MINUS_ONE = -1
    SLASH = '/'
